import { Facing, ModelPosition, Status } from './Player';

export const positions: Record<Status, Record<Facing, ModelPosition>> = {
  none: {
    left: {
      rightShoulder: 80,
      rightElbow: -120,
      rightHip: 110,
      rightKnee: 80,
      leftShoulder: 100,
      leftElbow: -115,
      leftHip: 90,
      leftKnee: 80,
    },
    right: {
      rightShoulder: 100,
      rightElbow: -60,
      rightHip: 70,
      rightKnee: 100,
      leftShoulder: 80,
      leftElbow: -65,
      leftHip: 90,
      leftKnee: 100,
    },
  },
  hit: {
    left: {
      rightShoulder: 180,
      rightElbow: -180,
      rightHip: 110,
      rightKnee: 80,
      leftShoulder: 100,
      leftElbow: -115,
      leftHip: 90,
      leftKnee: 80,
    },
    right: {
      rightShoulder: 0,
      rightElbow: 0,
      rightHip: 70,
      rightKnee: 100,
      leftShoulder: 100,
      leftElbow: -65,
      leftHip: 90,
      leftKnee: 100,
    },
  },
  forward: {
    left: {
      rightShoulder: 80,
      rightElbow: -120,
      rightHip: 90,
      rightKnee: 80,
      leftShoulder: 100,
      leftElbow: -115,
      leftHip: 110,
      leftKnee: 80,
    },
    right: {
      rightShoulder: 100,
      rightElbow: -60,
      rightHip: 90,
      rightKnee: 100,
      leftShoulder: 80,
      leftElbow: -65,
      leftHip: 70,
      leftKnee: 100,
    },
  },
  backward: {
    left: {
      rightShoulder: 80,
      rightElbow: -120,
      rightHip: 90,
      rightKnee: 80,
      leftShoulder: 100,
      leftElbow: -115,
      leftHip: 110,
      leftKnee: 80,
    },
    right: {
      rightShoulder: 100,
      rightElbow: -60,
      rightHip: 90,
      rightKnee: 100,
      leftShoulder: 80,
      leftElbow: -65,
      leftHip: 70,
      leftKnee: 100,
    },
  },
};
