export const positions = {
  dead: {
    left: {
      rightShoulder: 70,
      rightElbow: -260,
      rightHip: 110,
      rightKnee: 80,
      leftShoulder: 90,
      leftElbow: -260,
      leftHip: 90,
      leftKnee: 80,
      waist: -115,
    },
    right: {
      rightShoulder: 110,
      rightElbow: 80,
      rightHip: 70,
      rightKnee: 100,
      leftShoulder: 90,
      leftElbow: 80,
      leftHip: 90,
      leftKnee: 100,
      waist: -65,
    },
  },
  none: {
    left: {
      rightShoulder: 80,
      rightElbow: -120,
      rightHip: 110,
      rightKnee: 80,
      leftShoulder: 100,
      leftElbow: -115,
      leftHip: 90,
      leftKnee: 80,
      waist: -90,
    },
    right: {
      rightShoulder: 100,
      rightElbow: -60,
      rightHip: 70,
      rightKnee: 100,
      leftShoulder: 80,
      leftElbow: -65,
      leftHip: 90,
      leftKnee: 100,
      waist: -90,
    },
  },

  isHit: {
    left: {
      rightShoulder: 80,
      rightElbow: -120,
      rightHip: 110,
      rightKnee: 80,
      leftShoulder: 100,
      leftElbow: -115,
      leftHip: 90,
      leftKnee: 80,
      waist: -85,
    },
    right: {
      rightShoulder: 100,
      rightElbow: -60,
      rightHip: 70,
      rightKnee: 100,
      leftShoulder: 80,
      leftElbow: -65,
      leftHip: 90,
      leftKnee: 100,
      waist: -95,
    },
  },

  lefthit: {
    left: {
      rightShoulder: 75,
      rightElbow: -125,
      rightHip: 110,
      rightKnee: 80,
      leftShoulder: 180,
      leftElbow: -180,
      leftHip: 90,
      leftKnee: 80,
      waist: -90,
    },
    right: {
      rightShoulder: 105,
      rightElbow: -55,
      rightHip: 70,
      rightKnee: 100,
      leftShoulder: 0,
      leftElbow: 0,
      leftHip: 90,
      leftKnee: 100,
      waist: -90,
    },
  },

  righthit: {
    left: {
      rightShoulder: 180,
      rightElbow: -180,
      rightHip: 110,
      rightKnee: 80,
      leftShoulder: 95,
      leftElbow: -115,
      leftHip: 90,
      leftKnee: 80,
      waist: -90,
    },
    right: {
      rightShoulder: 0,
      rightElbow: 0,
      rightHip: 70,
      rightKnee: 100,
      leftShoulder: 85,
      leftElbow: -65,
      leftHip: 90,
      leftKnee: 100,
      waist: -90,
    },
  },

  block: {
    left: {
      rightShoulder: 115,
      rightElbow: -95,
      rightHip: 110,
      rightKnee: 80,
      leftShoulder: 130,
      leftElbow: -95,
      leftHip: 90,
      leftKnee: 80,
      waist: -90,
    },
    right: {
      rightShoulder: 65,
      rightElbow: -85,
      rightHip: 70,
      rightKnee: 100,
      leftShoulder: 50,
      leftElbow: -85,
      leftHip: 90,
      leftKnee: 100,
      waist: -90,
    },
  },

  forward: {
    left: {
      rightShoulder: 80,
      rightElbow: -120,
      rightHip: 90,
      rightKnee: 80,
      leftShoulder: 100,
      leftElbow: -115,
      leftHip: 110,
      leftKnee: 80,
      waist: -90,
    },
    right: {
      rightShoulder: 100,
      rightElbow: -60,
      rightHip: 90,
      rightKnee: 100,
      leftShoulder: 80,
      leftElbow: -65,
      leftHip: 70,
      leftKnee: 100,
      waist: -90,
    },
  },

  backward: {
    left: {
      rightShoulder: 80,
      rightElbow: -120,
      rightHip: 90,
      rightKnee: 80,
      leftShoulder: 100,
      leftElbow: -115,
      leftHip: 110,
      leftKnee: 80,
      waist: -90,
    },
    right: {
      rightShoulder: 100,
      rightElbow: -60,
      rightHip: 90,
      rightKnee: 100,
      leftShoulder: 80,
      leftElbow: -65,
      leftHip: 70,
      leftKnee: 100,
      waist: -90,
    },
  },
} as const;
